apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - 1password-item.yaml

helmCharts:
  - name: rabbitmq
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 15.0.2
    releaseName: "rabbitmq"
    namespace: rabbitmq
    includeCRDs: true
    valuesFile: values.yaml
