apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crawl-worker
  template:
    metadata:
      labels:
        app: crawl-worker
    spec:
      containers:
        - name: crawl-worker-container
          image: wjt40398/intrend-lab:crawl-worker-latest
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
      imagePullSecrets:
        - name: docker-secret
