# https://taskfile.dev/installation/
version: "3"

tasks:
  init:
    desc: Initialize the project
    cmds:
      - terraform init -upgrade
      # - go mod download

  # argocd:
  #   desk: Bootstrap argocd
  #   cmd:
  #     - ../k8s/bootstrap_argocd.sh

  create:
    desc: Create the cluster
    cmds:
      - terraform apply -auto-approve
      # - task argocd
      - ./get_talos_kubernetes_config.sh

  destroy:
    desc: Destroy the cluster
    cmds:
      - terraform destroy -target=null_resource.terraform-up -auto-approve
      - terraform destroy -auto-approve

  recreate:
    desc: Recreate the cluster
    cmds:
      - task destroy
      - task create
      # - task argocd
