apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s3-worker
  template:
    metadata:
      labels:
        app: s3-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - work-00
      containers:
        - name: s3-worker-container
          image: wjt40398/intrend-lab:s3-worker-latest
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
      imagePullSecrets:
        - name: docker-secret
