apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: data-harvesters
  namespace: argocd
  labels:
    intrend.lab: application
spec:
  generators:
    - git:
        repoURL: https://github.com/wtp43/Intrend-lab
        revision: HEAD
        directories:
          - path: k8s/apps/data-harvesters/*
  template:
    metadata:
      name: "{{ path.basename }}"
      labels:
        intrend.lab: application
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: data-harvesters
      source:
        repoURL: https://github.com/wtp43/Intrend-lab
        targetRevision: HEAD
        path: "{{ path }}"
      destination:
        name: in-cluster
        namespace: rabbitmq-workers
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
