apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/wtp43/Intrend-lab"
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "cert-manager"
      server: "*"
    - namespace: "crossplane"
      server: "*"
    - namespace: "node-feature-discovery"
      server: "*"
    - namespace: "intel-device-plugins"
      server: "*"
    - namespace: "kube-system"
      server: "*"
    - namespace: "sealed-secrets"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
