apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  intrend.app: message-queue
  app.kubernetes.io/managed-by: argocd

resources:
  - project.yaml
  - application-set.yaml
