prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    scrapeTimeout: "1s"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          selector:
            matchLabels:
              app: prometheus
alertmanager:
  alertmanagerspec:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
grafana:
  grafanaspec:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

