prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    scrapeTimeout: "1s"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          volumeName: pv-prometheus
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
alertmanager:
  alertmanagerspec:
    volumeClaimTemplate:
      spec:
        volumeName: pv-alertmanager
        storageClassName: longhorn
grafana:
  grafanaspec:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        volumeName: pv-grafana
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi

