apiVersion: apps/v1
kind: Deployment
metadata:
  name: ig-timeline-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ig-timeline-worker
  template:
    metadata:
      labels:
        app: ig-timeline-worker
    spec:
      containers:
        - name: ig-timeline-worker-container
          image: wjt40398/intrend-lab:ig-timeline-worker-latest
          imagePullPolicy: Always
          env:
            - name: PYTHONUNBUFFERED
              value: "0"
      imagePullSecrets:
        - name: docker-secret
