apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  sourceRepos:
    - "https://github.com/wtp43/Intrend-lab"
  destinations:
    - namespace: "argocd"
      server: "*"
    - namespace: "rabbitmq-workers"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
