apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.14.2
    releaseName: sealed-secrets-controller
    namespace: kube-system
    includeCRDs: true
    valuesInline:
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
    includeCRDs: true
    valuesFile: values.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

